# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/91867/Desktop/CPU/pipeline-cpu/Project_Src/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/Instrution_Memory/Instrution_Memory.xci
# IP: The module: 'Instrution_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/91867/Desktop/CPU/pipeline-cpu/Project_Src/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/Instrution_Memory/Instrution_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instrution_Memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/91867/Desktop/CPU/pipeline-cpu/Project_Src/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/Instrution_Memory/Instrution_Memory.xci
# IP: The module: 'Instrution_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/91867/Desktop/CPU/pipeline-cpu/Project_Src/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/Instrution_Memory/Instrution_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instrution_Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
