# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Data_Memory/Data_Memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Data_Memory || ORIG_REF_NAME==Data_Memory} -quiet] -quiet

# IP: ip/Instruction_Memory/Instruction_Memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Instruction_Memory || ORIG_REF_NAME==Instruction_Memory} -quiet] -quiet

# XDC: ip/Data_Memory/Data_Memory_ooc.xdc

# XDC: ip/Instruction_Memory/Instruction_Memory_ooc.xdc
